Electricity variables
iiasa/idesignres-workflow pull request #7
Opened 2024-12-19 17:03 UTC by enokandi

The yaml file containing newly defined electricity grid variables has been added.

2025-01-08 13:24 UTC, danielhuppmann reviewed
Here's an initial set of review comments for this PR.

2025-01-08 13:24 UTC, danielhuppmann commented on definitions/variable/grids infrustructure/electricity_grid.yaml
> +- Network|Electricity|Resistance
Missing semi-colon after the variable, also in other places.
```suggestion
- Network|Electricity|Resistance:
```

2025-01-08 13:24 UTC, danielhuppmann commented on definitions/variable/grids infrustructure/electricity_grid.yaml
> + - Marginal Active Power|Electricity|Demand|Share of Total:
Per new IAMC convention, operations/method should be added in square brackets.

**But** it's really not clear to me what *marginal* active power is...
```suggestion
 - Marginal Active Power|Electricity|Demand [Share]:
```

2025-01-08 13:24 UTC, danielhuppmann commented on definitions/variable/grids infrustructure/electricity_grid.yaml
> +    unit: 'GW'
No quotation marks needed unless the unit (or any other attribute) starts with yaml-specific characters.
```suggestion
    unit: GW
```

2025-01-08 13:24 UTC, danielhuppmann commented on definitions/variable/grids infrustructure/electricity_grid.yaml
> +    unit: '-'
Dimensionless variables should have an empty unit.
```suggestion
    unit:
```

2025-01-08 13:24 UTC, danielhuppmann commented
fyi @JKNTNU

2025-01-08 13:28 UTC, JKNTNU commented
[like]  Jannis Kerl reacted to your message:
________________________________
From: Daniel Huppmann ***@***.***>
Sent: Wednesday, January 8, 2025 1:24:50 PM
To: iiasa/idesignres-workflow ***@***.***>
Cc: Jannis Kerl ***@***.***>; Mention ***@***.***>
Subject: Re: [iiasa/idesignres-workflow] Electricity variables (PR #7)


fyi @JKNTNU<https://github.com/JKNTNU>

—
Reply to this email directly, view it on GitHub<https://github.com/iiasa/idesignres-workflow/pull/7#issuecomment-2577665861>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BNB6JGX7QXS2HMXR3VQWRED2JURKFAVCNFSM6AAAAABT5NVQD2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNZXGY3DKOBWGE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-01-09 10:53 UTC, enokandi commented
Thanks, dear Daniel, for your comments.

Before updating my PR, I wanted to ask about the level of freedom we have in defining variables. For example, for generation unit types, we have more detailed data than what is currently reflected in the existing nomenclature. Taking gas-fired generation units as an example, the nomenclature currently provides only “Capacity|Electricity|Gas.” However, we need more specificity, such as “Capacity|Electricity|Gas|Combined Cycle” or “Capacity|Electricity|Gas|Steam Turbine.”

I’m not sure if we’re allowed to define new variables like these or if doing so might cause conflicts with other variables, such as “Marginal Cost|Electricity|Gas|w/ CC” or “Marginal Cost|Electricity|Gas|w/o CC.”

2025-01-09 14:08 UTC, danielhuppmann commented
The newly added variables should be consistent with the variables in **common-definitions**, so specifically for your examples:
1. There are variables like "Capacity|Electricity|Gas", so adding "Capacity|Electricity|Gas|Combined Cycle" in this project repository makes sense.
2. There are variables like "Capital Cost|..." in **common-definitions**, so adding "Operational Cost|..." and "Fixed Cost|..." (or similar) makes sense.

2025-01-10 10:11 UTC, danielhuppmann requested changes
Thanks! A few more suggestions plus an explanation for using tag-lists, which would make this file much readable and shorter.

2025-01-10 10:11 UTC, danielhuppmann commented on definitions/variable/grids infrustructure/electricity_grid.yaml
> +    unit: GW
Are these variables really necessary? A gas turbine will always be used with Natural Gas, not other Fossil Fuels... Also, it is confusing that the other types of gas power plants are not listed here. So better to remove.

2025-01-10 10:11 UTC, danielhuppmann commented on definitions/variable/grids infrustructure/electricity_grid.yaml
> +- Capacity|Electricity|Solar|Thermal:
Is this really a thing?

2025-01-10 10:11 UTC, danielhuppmann commented on definitions/variable/grids infrustructure/electricity_grid.yaml
> +    unit: GW
You could simplify this file by using a tag-list, so creating a separate file `tag_power_turbine_types.yaml` (or similar) that has
```yaml
- Turbine Type:
    - Combined Cycle:
        description: combined-cycle (CC)
    - Gas Turbine:
         description: gas turbines (GT)
    - Integrated Gasification Combined-Cycle:
        description: integrated gasification combined cycle plants (IGCC)
    - Steam Turbine:
        description: steam turbines
```
And then simplify this section
```suggestion
- Capacity|Electricity|Gas|{Turbine Type}:
    description: Installed (available) capacity to generate electricity with natural gas
      using {Turbine Type} plants
    unit: GW
```
Same for all other variables that use all combinations of turbines.

This produces a much more concise and readable variable list file. The nomenclature package will automatically create all permutations during scenario validation.

2025-01-10 11:28 UTC, enokandi commented on definitions/variable/grids infrustructure/electricity_grid.yaml
> +    unit: GW
Hi Again Daniel. Thank you for your comments. The point is that Gas Turbine units do not use Natural Gas as their fuel necessarily. The word gas in gas turbine refers to the fluid used to drive the turbine, similar to water vapor in steam turbines.

2025-01-10 11:38 UTC, enokandi commented on definitions/variable/grids infrustructure/electricity_grid.yaml
> +- Capacity|Electricity|Solar|Thermal:
Yes. These units utilize sunlight to heat fluids, generating steam to drive turbines and produce electricity. Spain, particularly, has a considerable installed capacity of this type.

2025-01-10 11:41 UTC, enokandi commented on definitions/variable/grids infrustructure/electricity_grid.yaml
> +- Capacity|Electricity|Solar|Thermal:
Still, if you think adding a new technology like this might be challenging for the nomenclature used throughout the whole project, I can omit it and categorize those units simply as solar units.

2025-01-10 11:43 UTC, danielhuppmann commented on definitions/variable/grids infrustructure/electricity_grid.yaml
> +- Capacity|Electricity|Solar|Thermal:
Ok, is that the same as Concentrated Solar Power (CSP)? If yes, I suggest to use CSP to remain consistent with **common-definitions**.

There, we use "Final Energy|Solar" for thermal heat, but for water-heating, see [here](https://github.com/IAMconsortium/common-definitions/blob/d15f81a1c9670ddf6562aaa9a88224ba716f1ac9/definitions/variable/energy/final-energy.yaml#L70)

2025-01-10 11:57 UTC, danielhuppmann commented on definitions/variable/grids infrustructure/electricity_grid.yaml
> +    unit: GW
Fair enough (I meant that oil-based gas turbines are probably not really used any more, right?).

But that still doesn't mean that we need a part-aggregate "Fossil". After all, you could also run it with Hydrogen, which could or could not be from fossil sources...

2025-01-10 14:38 UTC, enokandi commented on definitions/variable/grids infrustructure/electricity_grid.yaml
> +- Capacity|Electricity|Solar|Thermal:
You are right. Thanks for pointing it out. 
I removed Capacity|Electricity|Solar|Thermal and replaced Thermal with CSP for Marginal Cost|Electricity|Solar|CSP.

2025-01-10 14:39 UTC, enokandi commented on definitions/variable/grids infrustructure/electricity_grid.yaml
> +    unit: GW
It's done now.

2025-01-13 13:46 UTC, danielhuppmann commented on definitions/variable/grids infrustructure/electricity_grid.yaml
> +    unit: GW
Diesel-fired power plants should be reported as "Oil", or is there any reason against that?

2025-01-13 13:52 UTC, danielhuppmann commented
Almost there, please remove "Capacity|Electricity|Fossil|{Turbine Type}:" (or split "Oil" into different components if this is necessary and relevant)

2025-01-14 15:52 UTC, enokandi commented
> Almost there, please remove "Capacity|Electricity|Fossil|{Turbine Type}:" (or split "Oil" into different components if this is necessary and relevant)

Hi Daniel. I removed both "Capacity|Fossil" and "Marginal Cost|Fossil" as you asked. As a result, we currently have no representation for diesel, so we need to combine it with oil. Does that seem correct to you?

Regarding the term “Marginal Cost,” here at NTNU, we discussed using “Variable Cost” and “Fixed Cost” instead. Therefore, the total generation cost would consist of fixed, variable, and fuel costs. We also agreed that “Variable Cost” is more accurate than “Operation Cost.” I’d like to get your opinion on this as well.

2025-01-14 16:08 UTC, danielhuppmann commented
About “Marginal Cost” vs. “Variable Cost” vs. “Operational Cost”, all are ok. But I find it confusing that you do not include fuel costs in that. From my understanding about power systems, linear costs excluding fuel costs are small compared to the other components, and variable costs usually include all linear costs in simple models that do not model input fuels endogenously. 

Are you planning to also add variables for “Fuel Cost”?

if yes, I would stick with “Operational Cost” for the non-fuel linear component to avoid confusion.

2025-01-14 16:27 UTC, enokandi commented
> About “Marginal Cost” vs. “Variable Cost” vs. “Operational Cost”, all are ok. But I find it confusing that you do not include fuel costs in that. From my understanding about power systems, linear costs excluding fuel costs are small compared to the other components, and variable costs usually include all linear costs in simple models that do not model input fuels endogenously.
> 
> Are you planning to also add variables for “Fuel Cost”?
> 
> if yes, I would stick with “Operational Cost” for the non-fuel linear component to avoid confusion.

No actually. The idea here was to have both Variable Cost and Fuel Cost individually, similar to the Empire model. So I replaced Marginal cost with Variable cost.

2025-01-14 16:29 UTC, enokandi commented
Moreover, I removed IGCC from turbine technologies and used abbreviations (CCGT and OCGT) to make it consistent with Jannis.

2025-01-15 15:40 UTC, danielhuppmann commented
It seems to me that this PR has overlap with #9, so let's wait until that PR is merged and then revisit.

2025-01-21 12:39 UTC, closed without merging